services:

  base:
    image: localhost/omeka-base:4.1.1
    build:
      context: ../../base

  didoc-db:
    image: docker.io/library/mariadb:11.8.5
    container_name: didoc-db
    depends_on:
      - base
    environment:
      MARIADB_DATABASE: "didoc"
      MARIADB_ROOT_USER: "root"
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/didoc-mysql-root-pw
      MARIADB_USER: "didoc"
      MARIADB_PASSWORD_FILE: /run/secrets/didoc-mysql-pw
    volumes:
      - didoc_db:/var/lib/mysql
    ports:
      - ${ENV_DB_PORTS}
    secrets:
      - didoc-mysql-root-pw
      - didoc-mysql-pw

  didoc-web:
    container_name: didoc-web
    build: 
      context: .
      args:
        MODULE_AdvancedResourceTemplate_VERSION: "3.4.45"
        MODULE_AdvancedSearch_VERSION: "3.4.55"
        MODULE_AnalyticsSnippet_VERSION: "3.4.5"
        MODULE_AnalyticsSnippetPiwik_VERSION: "3.4.8"
        MODULE_BlockPlus_VERSION: "3.4.42"
        MODULE_CleanUrl_VERSION: "3.17.10"
        MODULE_Common_VERSION: "3.4.76"
        MODULE_CopyResources_VERSION: "1.0.1"
        MODULE_CSSEditor_VERSION: "1.3.1"
        MODULE_CSVImport_VERSION: "2.6.2"
        MODULE_CustomVocab_VERSION: "2.0.2"
        MODULE_FacetedBrowse_VERSION: "1.8.0"
        MODULE_InverseProperties_VERSION: "1.1.1"
        MODULE_Internationalisation_VERSION: "3.4.17"
        MODULE_Mapping_VERSION: "2.2.0"
        MODULE_MetadataBrowse_VERSION: "1.6.0"
        MODULE_NumericDataTypes_VERSION: "1.13.0"
        MODULE_Reference_VERSION: "3.4.57"
        MODULE_Thesaurus_VERSION: "3.4.22"
        THEME_ThanksRoy_VERSION: "1.2.2"
    ports:
      - ${ENV_PORTS}
    depends_on:
      - didoc-db
    environment:
      MARIADB_DATABASE: "didoc"
      MARIADB_USER: "didoc"
      MARIADB_PASSWORD_FILE: /run/secrets/didoc-mysql-pw
      MARIADB_HOST: "didoc-db"
    volumes:
      - ${ENV_VOLUME}
    secrets:
      - didoc-mysql-pw

volumes:
  didoc_db:

secrets:
  didoc-mysql-root-pw:
    external: true
  didoc-mysql-pw:
    external: true
