services:

  base:
    image: localhost/omeka-base:4.1.1
    build:
      context: ../../base
      args:
        OMEKA_S_VERSION: "4.1.1"

  didoc-db:
    image: docker.io/library/mariadb:latest
    container_name: didoc-db
    depends_on:
      - base
    environment:
      MYSQL_DATABASE: ${ENV_MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${ENV_MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${ENV_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${ENV_MYSQL_USER}
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD}
    volumes:
      - didoc_db:/var/lib/mysql

  didoc-web:
    container_name: didoc-web
    build: 
      context: .
      args:
        MODULE_AdvancedResourceTemplate_VERSION: "3.4.45"
        MODULE_AnalyticsSnippet_VERSION: "3.4.5"
        MODULE_AnalyticsSnippetPiwik_VERSION: "3.4.8"
        MODULE_BlockPlus_VERSION: "3.4.42"
        MODULE_CleanUrl_VERSION: "3.17.10"
        MODULE_Common_VERSION: "3.4.72"
        MODULE_CopyResources_VERSION: "1.0.1"
        MODULE_CSSEditor_VERSION: "1.3.1"
        MODULE_CSVImport_VERSION: "2.6.2"
        MODULE_CustomVocab_VERSION: "2.0.2"
        MODULE_FacetedBrowse_VERSION: "1.8.0"
        MODULE_InverseProperties_VERSION: "1.1.1"
        MODULE_Mapping_VERSION: "2.2.0"
        MODULE_MetadataBrowse_VERSION: "1.6.0"
        MODULE_NumericDataTypes_VERSION: "1.13.0"
        THEME_ThanksRoy_VERSION: "1.2.2"
    ports:
      - ${ENV_PORTS}
    depends_on:
      - didoc-db
    environment:
      MYSQL_DATABASE: ${ENV_MYSQL_DATABASE}
      MYSQL_USER: ${ENV_MYSQL_USER}
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD}
      MYSQL_HOST: didoc-db    
    volumes:
      - ${ENV_VOLUME}

volumes:
  didoc_files:
  didoc_db:
